baseURL = "http://somethingweate.com"
theme = "neckbeard"
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true
metaDataFormat = "toml"
publishDir = "docs"

[params]
title = "Something We Ate"
description = "making something to eat"
author = "henderjon"
copyrightOwner = "somethingweate.com"
copyrightStartYear = "2015"
favicon = "imgs/favicon.ico"

[params.additional]
css = ["css/custom.css"]
js = []

[taxonomies]
tag = "tags"

[social]
# email = "contact@example.com"
github = "https://github.com/henderjon"
instagram = "https://instagram.com/somethingweate"

[permalinks]
page = "/:slug/"
posts = "posts/:title/"

# [[menu.main]]
# name = "home"
# weight = -70
# identifier = "nav"
# url = "/"


